#!/bin/sh

# apps
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-center "$HOME/.local/share/bg" &
$XDG_CONFIG_HOME/polybar/launch.sh &
picom &
unclutter -b --timeout 3 &

# monitors
if xrandr | grep "HDMI-2 disconnected" ; then
	bspc monitor 'eDP-1' -d I II III IV V VI VII VIII IX X
else
	xrandr --output 'eDP-1' --pos 320x1080 --auto --output 'HDMI-2' --mode 2560x1080 --primary --pos 0x0
	bspc monitor 'eDP-1' -d I II III
	bspc monitor 'HDMI-2' -d  IV V VI VII VIII IX X
fi

# window
bspc config border_width        1
bspc config window_gap          15
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        5
bspc config right_padding       5
#bspc config window_gap         0
bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     true
bspc config automatic_scheme    alternate
bspc config initial_polarity    second_child
bspc config center_pseudo_tiled false

# monitor
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# pointer
bspc config pointer_follows_focus       true
bspc config focus_follows_pointer       true

# remove all rules before wm restart
bspc rule -r "*"

# rules
#bspc rule -a KeePassXC state=floating follow=on rectangle=800x600+0+0
bspc rule -a MEGAsync state=floating border=off rectangle=402x564+1500+30

# colors
## Solarized Dark
#bspc config normal_border_color        "#002b36"
#bspc config active_border_color        "#002b36"
#bspc config focused_border_color       "#eee8d5"
#bspc config presel_feedback_color      "#eee8d5"
#bspc config focused_border_color       "#2aa198"
#bspc config presel_feedback_color      "#2aa198"
## One Dark
#bspc config normal_border_color         "#1e2127"
#bspc config active_border_color         "#1e2127"
#bspc config focused_border_color        "#abb2bf"
#bspc config presel_feedback_color       "#abb2bf"
## palenight
bspc config normal_border_color         "#434758"
bspc config active_border_color         "#434758"
bspc config focused_border_color        "#d0d0d0"
bspc config presel_feedback_color       "#d0d0d0"
## Nord
#bspc config normal_border_color        "#2e3440"
#bspc config active_border_color        "#2e3440"
#bspc config focused_border_color       "#d8dee9"
#bspc config presel_feedback_color      "#d8dee9"
## Tomorrow Dark
#bspc config normal_border_color        "#1d1f21"
#bspc config active_border_color        "#1d1f21"
#bspc config focused_border_color       "#c5c8c6"
#bspc config presel_feedback_color      "#c5c8c6"
## Isotope Dark
#bspc config normal_border_color        "#000000"
#bspc config active_border_color        "#000000"
#bspc config focused_border_color       "#d0d0d0"
#bspc config presel_feedback_color      "#d0d0d0"
## Twilight
#bspc config normal_border_color        "#1e1e1e"
#bspc config active_border_color        "#1e1e1e"
#bspc config focused_border_color       "#a7a7a7"
#bspc config presel_feedback_color      "#a7a7a7"
